spring:
  application:
    name: discovery-server
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: false