#spring:
#  application:
#    name: seller-service
#  jpa:
#    show-sql: true
#    properties:
#      hibernate: 
#        format_sql: true
#  datasource:
#    hikari:
#      minimum-idle: 3
#      maximum-pool-size: 7
#      connection-test-query: select 1;
#      connection-timeout: 300000
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://47.75.176.242:30005/foodmarket?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
#    username: root
#    password: 1JKkU0lG6o

#server:
#  port: 8803
#  servlet:
#    path: /seller

#eureka:
#  client:
#    enabled: false
#    service-url:
#      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
#
#logging:
#  level:
#    org.springframework.web: DEBUG
